# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170610_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
